-- List each pair of actors that have worked together.
SELECT FA1.ACTOR_ID AS ACTOR_01, FA2.ACTOR_ID AS ACTOR_02, FA1.FILM_ID
FROM SAKILA.FILM_ACTOR FA1
INNER JOIN SAKILA.FILM_ACTOR FA2 
ON FA1.FILM_ID = FA2.FILM_ID
AND FA1.ACTOR_ID <> FA2.ACTOR_ID;

WITH CTE_ACTORS_PLAYED_TOGETHER AS (
	SELECT FA1.ACTOR_ID AS ACTOR_01, FA2.ACTOR_ID AS ACTOR_02, FA1.FILM_ID
    FROM SAKILA.FILM_ACTOR FA1
    INNER JOIN SAKILA.FILM_ACTOR FA2
    ON FA1.FILM_ID = FA2.FILM_ID
    AND FA1.ACTOR_ID <> FA2.ACTOR_ID
)
SELECT * 
FROM CTE_ACTORS_PLAYED_TOGETHER;

-- For each film, list actor that has acted in more films.

